---
#!/bin/bash
# Copyright 2023, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Create local users (optional)
#- import_tasks: users.yml
#  when: create_local_user

- name: Create ORD networks
  openstack.cloud.network:
    cloud: ord1
    state: present
    name: ext_network
    provider_network_type: vlan
    provider_physical_network: physnet1
    provider_segmentation_id: 1200
    external: true

- name: Create ORD subnets
  openstack.cloud.subnet:
    cloud: ord1
    state: present
    network_name: ext_network
    name: ext_subnet_161.47.161.192/26
    cidr: 161.47.161.192/26
    allocation_pool_start: 161.47.161.199
    allocation_pool_end: 161.47.161.254
    dns_nameservers:
       - 8.8.4.4
       - 8.8.8.8
    host_routes:
       - destination: 0.0.0.0/0
         nexthop: 161.47.161.193
